Traceback (most recent call last):
  File "train.py", line 30, in <module>
    nn, optim, loss_fn = configuration.configure(configuration_script)
  File "/Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/DA6401 Assignment/da6401_assignment1/configure.py", line 27, in configure
    assert type(script['loss_function']) == str
KeyError: 'loss_function'
